### ISSUE TITLE
Renseigner une unité pour les seuils dans les barèmes (Scale)

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1019]
Contexte: je veux créer une législation vieillie: la version de la législation actuelle où tous les paramètres seraient inflatés. J'ai donc besoin de reconnaître tous les paramètres qui sont des montants monétaires pour les inflater.

Les différents barèmes utilisés par openfisca n'ont pas tous des seuils qui sont des montants en euros.
Par exemple les seuils des tranches de l'IR sont en euros mais les les tranches des cotisations sociales sont souvent exprimés en multiple du plafond de la sécurité sociale.

Je pense que cette information est très importante et qu'il serait utile que l'on puisse la renseigner.
Cela veut dire rajouter un champ `unit` aux seuils. Je pense que le moins redondant est d'avoir un champ `unit` commun à tous les seuils du barème. La valeur de ce champ pourrait être monetary ou pointer vers un autre paramètre comme le plafond de la sécurité sociale.

Je poste dans ici et pas dans core afin que l'on s'accorde sur ce qui est le plus pratique avec un cas d'usage évident. Puis on pourra compléter ce qui est fait [ici](https://github.com/openfisca/openfisca-core/pull/681).

Qu'en pensez-vous @fpagnoux @sandcha @Anna-Livia ?

**Comment by fpagnoux** [comment]
Question intéressante...

Il faudrait peut être trancher avant de merger https://github.com/openfisca/country-template/pull/49 et https://github.com/openfisca/openfisca-core/pull/681.

https://github.com/openfisca/openfisca-core/pull/681 permet d'ajouter un champs `unit` à un barème, mais est-ce que ça a vraiment du sens? On ne sait pas si c'est l'unité des seuils, des taux, ou des résultats de l'application du barème... 

On pourrait ajouter une métadonnée `threshold_unit` aux barèmes, et considérer que `unit` s'applique aux "valeurs" (taux, taux moyen, ou autre)

Ça donnerait:

```yaml
brackets:
  - rate:
      2001-04-01:
        value: 0.012
    threshold:
      2001-04-01:
        value: 0.0
  - rate:
      2001-04-01:
        value: 0.013
    threshold:
      2001-04-01:
        value: 1.0
  - rate:
      2001-04-01:
        value: 0.0
    threshold:
      2001-04-01:
        value: 4.0
description: AGFF
threshold_unit: Plafonds BMAF
rate_unit: /1
```
