### ISSUE TITLE
Problème calcul de l'allocation de base de la PAJE

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1109]
La formule de `paje_base` semble avoir un problème. Sur données fiscales (via le CASD), on simule 1,4 milliards de dépenses au lieu de 4 milliards environ pour 2016. Le problème semble venir de la manière dont `est_plus_jeune_enfant` est directement calculé dans la formule de `paje_base`. Lorsqu'on crée cette dummy de plus jeune enfant directement dans les données (via le modèle `taxipp` sous CASD), et qu'on ajoute cette variable en input variable à part entière, on tombe sur la bonne masse de dépenses.

Question : comment calculer cette dummy de manière propre sous OpenFisca France ?

Autre remarque : le nom `est_plus_jeune_enfant` est inapproprié, car comme c'est calculé, il s'agit de la plus jeune *personne* (et non du plus jeune enfant) de la famille.

**Comment by Morendil** [comment]
@bfabre01 Tu aurais moyen d'isoler un jeu de données restreint qui mette en évidence cet écart, afin de le reproduire sans avoir à passer par le CASD ? Histoire de cibler l'investigation, les 4 milliards vs 1,4 sont calculés sur une population de combien de personnes et foyers ?

**Comment by bfabre01** [comment]
@Morendil : c'est compliqué d'isoler un jeu de données venant du CASD. En revanche, ce que je peux dire, c'est que l'erreur provient de la définition du terme `est_plus_jeune_enfant` présent dans la formule, ce qui cible pas mal l'investigation. Le seul fait de la définir à la main fait passer l'agrégat de 1,4 à 4 milliards, sans rien changer d'autre. Ces agrégats sont simulés sur données fiscales couvrant la France entière (c'est-à-dire environ 37 millions de foyers fiscaux, 33 millions de familles et 67 millions d'individus).

**Comment by bfabre01** [comment]
Quand je dis qu'on redéfinit le terme `est_plus_jeune_enfant`, ça veut dire que l'on définit dans le tax and benefit system une input variable portant ce nom (définie au niveau individuel et mensuel). Puis, on construit cette variable en amont dans nos données. Puis, dans la formule de `paje_base`, le terme `est_plus_jeune_enfant` est appelé comme suit:
`est_plus_jeune_enfant = famille.members('est_plus_jeune_enfant', period)`

**Comment by Morendil** [comment]
On en a discuté un peu avec @guillett ce matin, sur la base de cette conversation je soupçonne une erreur liée au calcul vectoriel et à sa nature contre-intuitive.

Ma compréhension est que la ligne suivante:

` min(famille.members('age', period))`

renvoie le résultat attendu si le vecteur contenu dans l'entité `famille` ne contient qu'un seul élément (une famille). Par contre s'il contient plusieurs familles, `famille.members('age', period)` renvoie **les âges de tous les individus de toutes les familles**, cet appel va donc renvoyer le plus petit élément du vecteur, et ce sera donc **l'âge minimum des membres de toutes les familles du scénario**.

Je n'ai pas de solution à proposer pour l'instant, j'ai le sentiment qu'il faut appliquer la fonction `min` "vectoriellement" mais je ne maîtrise pas encore assez NumPy. @guillett a parlé de "matrice de passage" mais ce n'était pas clair pour moi.

**Comment by benjello** [comment]
Arrgh.
En même temps cela m'étonnerait que @fpagnoux ait laissé passé cela ?
Ne faudrait-il pas utiliser plutôt [cela](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/entities.py#L602) ?

**Comment by Morendil** [comment]
@benjello Empiriquement, sur un cas de test avec un petit vecteur:

```
> famille.members('age',period)
array([40,  1, 40,  1], dtype=int32)
> famille.min(famille.members('age',period))
array([1., 1.])
```

A part la conversion int->float, ça me semble déjà mieux.

**Comment by Morendil** [comment]
Bon il me semble que ce qui suit est un cas minimal de reproduction. Le test passe au vert si on supprime purement et simplement l'évaluation de `est_plus_jeune_enfant` et `age_plus_jeune_enfant`.

Idée saugrenue: demander au test runner de transformer systématiquement les cas individuels en vecteurs de deux familles strictement identiques. Je me demande si ça détecterait une certaine quantité de bugs liés à la prise en main du calcul vectoriel…

```
- name: "Erreur la formule de la PAJE lors du calcul sur un vecteur de > 1 famille"
  period: 2018-02
  relative_error_margin: 0.01
  individus:
    - id: "parent1"
      age: 40
      salaire_imposable: 20000
      aah: 0
      etudiant: 0
      hsup: 0
    - id: "enfant1"
      date_naissance: 2016-01-01
      age: 2
      salaire_imposable: 0
      aah: 0
      etudiant: 0
      hsup: 0
    - id: "parent2"
      age: 40
      salaire_imposable: 20000
      aah: 0
      etudiant: 0
      hsup: 0
    - id: "enfant2"
      date_naissance: 2017-01-01
      age: 1
      salaire_imposable: 0
      aah: 0
      etudiant: 0
      hsup: 0
  familles:
    -
      parents: ["parent1"]
      enfants: ["enfant1"]
      partiel1: false
      af_nbenf: 1
      prestations_familiales_base_ressources: 20000
      empl_dir: 0
      ass_mat: 1
      gar_dom: 0
    -
      parents: ["parent2"]
      enfants: ["enfant2"]
      partiel1: false
      af_nbenf: 1
      prestations_familiales_base_ressources: 20000
      empl_dir: 0
      ass_mat: 1
      gar_dom: 0
  foyers_fiscaux:
    declarants: ["parent1"]
    personnes_a_charge: ["enfant1"]
  menages:
    personne_de_reference: "parent1"
    enfants: ["enfant1"]
  output_variables:
    paje_cmg: 703.81
    # BMAF 2017-04-01 = 407.84
    paje_base: 0.45950 * 407.84
    paje_naissance: 0
    paje_prepare: 0
    paje: 703.81 + (0.45950 * 407.84)

```
