### ISSUE TITLE
Corriger le calcul des âges

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1345]
Je m'attendrais à ce que le test suivant soit passant:
```YAML
- period: 2018-03
  absolute_error_margin: 0.03
  input:
    famille:
      parents: [parent1, parent2]
      enfants: [enfant1, enfant2]
    foyer_fiscal:
      declarants: [parent1, parent2]
      personnes_a_charge: [enfant1, enfant2]
    menage:
      personne_de_reference: parent1
      conjoint: parent2
      enfants: [enfant1, enfant2]
    individus:
      parent1:
        age: 38
      parent2:
        age: 35
      enfant1:
        date_naissance: 2018-01-01
      enfant2:
        date_naissance: 2018-01-01
  output:
    age: [38, 35, 0, 0]
```

…ce n'est pas le cas:
```
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.7.0, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /app, inifile: setup.cfg
collected 12 items

tests/formulas/age.yaml ...........F

================================================================================================================== FAILURES ==================================================================================================================
________________________________________________________________________________________________________________ test session ________________________________________________________________________________________________________________
/app/tests/formulas/age.yaml:
  Test '':
    age@2018-03: [   38.    35. -9999. -9999.] differs from [38. 35.  0.  0.] with an absolute margin [   0.    0. 9999. 9999.] > 0.03
==================================================================================================== 1 failed, 11 passed in 0.09 seconds =====================================================================================================
```

Cela semble notamment conduire à des résultats aberrants de `af_nbenf` et potentiellement fausser les calculs de prestations comme la PAJE.
