### ISSUE TITLE
Application du complément dégressif des allocations familiales, DOM + 1 enfant

### ISSUE THREAD

**Issue by denismerigoux** [openfisca/openfisca-france#1426]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai fait tourner le cas de test suivant sur OpenFisca (cloné directement depuis `master`) :

```yaml
- name: Allocations familiales - Cas N°1
  description: Montant AF
  period: 2019-01
  absolute_error_margin: 0.02
  input:
    famille:
      parents: [parent1, parent2]
      enfants: [enfant1]
    foyer_fiscal:
      declarants: [parent1, parent2]
      personnes_a_charge: [enfant1]
    menage:
      personne_de_reference: parent1
      conjoint: parent2
      enfants: [enfant1]
      residence_dom: true
      residence_mayotte: false
    individus:
      parent1:
        age: 38
        revenu_assimile_salaire:
          # 62533 est égal au premier plafond de modulation des allocations
          # familiales dans le cas d'un enfant à charge.
          # Ici, le revenu est calculé de telle sorte que l'on se place
          # juste au dessus du plafond en termes de ressources de base
          # des allocations familiales.
          2016: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2017: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2018: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2019: 62533 / 0.90 / 2 + 20 / 0.90 / 2
      parent2:
        age: 35
        revenu_assimile_salaire:
          2016: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2017: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2018: 62533 / 0.90 / 2 + 20 / 0.90 / 2
          2019: 62533 / 0.90 / 2 + 20 / 0.90 / 2
      enfant1:
        age: 10
  output:
    af_taux_modulation: 0.5
    af_base: 12.11
    af_majoration: 0
    # Jusqu'ici, tout va bien. Cependant, nous sommes ici dans le cas d'un ménage
    # à un enfant en DOM hors Mayotte. Le deuxième alinéa de l'article L. 755-12
    # du code de la sécurité sociale stipule:
    # "Toutefois, les quatre derniers alinéas de l’article L. 521-1 ne sont pas applicables lorsque le
    #  ménage ou la personne a un seul enfant à charge."
    # Or, le dernier alinéa de l'article L. 521-1 correspond au complément dégressif
    # des allocations familiales et de leur majoration. Ce complément dégressif
    # ne devrait pas donc être versé dans cette situation.
    # Or, il est ici versé.
    af_complement_degressif: 10.4
    # Les allocations famililes sont bien la somme de la base et du complément.
    af: 22.52
```

Comme l'indique le raisonnement juridique, je m'attendais ici à ce que le complément dégressif soit nul. Il s'agit d'une condition manquante sur https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/af.py#L246. Je peux me charger de faire une pull request, mais je voulais vérifier si vous êtes d'accord avec mon interprétation.

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [x] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

Doctorant en informatique, je réfléchis à la manière de modéliser la loi en utilisant des langages de programmation, et me suis penché sur l'implémentation des allocations familiales en tant qu'exemple pour motiver mon étude.
