### ISSUE TITLE
Pas le même résultat que la simulation IR du gouvernement

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1479]
Bonjour,

Je suis en train de tester si OpenFisca fonctionne bien sur les revenus de 2020, mais je n'arrive pas à retrouver les chiffres que j'attends. 

### Qu'ai-je fait ?
J'ai exécuté la requête suivante dans l'API OF : 
```
{
  "individus": {
    "Adulte 1": {
      "revenu_assimile_salaire": {
        "2020": 100000
      }
    },
    "Adulte 2": {},
    "Enfant 1": {
      "age": {
        "2020": 10
      }
    }
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Adulte 1",
        "Adulte 2"
      ],
      "personnes_a_charge": [
        "Enfant 1"
      ],
      "ip_net": {
        "2020": null
      }
    }
  }
}
```
(couple, 1 enfant à charge, 100_000 EUR de revenus en 2020)

### À quoi m'attendais-je ?
Je m'attendais à ce qu'elle me donne comme résultat 
```
      "ip_net": {
        "2020": 13442
      },
```
comme ce que retourne le formulaire des impôts 2021 sur les revenus 2020 : 
```
https://www3.impots.gouv.fr/simulateur/cgi-bin/calc-2021.cgi?pre_situation_residence=M&pre_situation_famille=M&0DA=1970&0DB=1970&0CF=1&0F0=2010&1AJ=100000
```
![gouv](https://i.imgur.com/DH9hgwS.png)

### Que s'est-il passé en réalité ?
L'API me retourne 
```
      "ip_net": {
        "2020": 13468
      },
```

### Voici des informations qui peuvent aider à reproduire le problème :
Lorsque je change l'année pour me baser sur les revenus de 2019 : 
```
{
  "individus": {
    "Adulte 1": {
      "revenu_assimile_salaire": {
        "2019": 100000
      }
    },
    "Adulte 2": {},
    "Enfant 1": {
      "age": {
        "2019": 10
      }
    }
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Adulte 1",
        "Adulte 2"
      ],
      "personnes_a_charge": [
        "Enfant 1"
      ],
      "ip_net": {
        "2019": null
      }
    }
  }
}
```
j'obtiens bien à l'Euro près le même résultat que lorsque j'appelle le simulateur des impôts 2020 sur les revenus 2019 : 
```
https://www3.impots.gouv.fr/simulateur/cgi-bin/calc-2020.cgi?pre_situation_residence=M&pre_situation_famille=M&0DA=1970&0DB=1970&0CF=1&0F0=2010&1AJ=100000
```
![gouv](https://i.imgur.com/rwO58J9.png)
```
      "ip_net": {
        "2019": 13721
      }
```

Ce n'est qu'un exemple, mais quand je teste avec plein de cas de figures, je retrouve des écarts entre OF et le site des impôts, alors qu'en 2019, c'était souvent les "bonnes" valeurs retournées.

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by sandcha** [comment]
Bonjour @PhunkyBob, Merci pour cette remontée d'erreur !
À ma connaissance, les deux mises à jour du calcul de l'impôt 2021 proviennent des PR #1472 et #1473.
Aurions-nous omis une mise à jour @bfabre01 @clallemand ? 🤔  

Dans le cas où vous souhaiteriez tester l'équivalent de la requête au format YAML, la voici transcrite : 
```yaml
- name: IRPP
  period: 2020
  input:
    famille:
      parents: [parent1, parent2]
      enfants: [enfant1]
    foyer_fiscal:
      declarants: [parent1, parent2]
      personnes_a_charge: [enfant1]
    menage:
      personne_de_reference: parent1
      conjoint: parent2
      enfants: [enfant1]
    individus:
      parent1:
        age: 42
        revenu_assimile_salaire:
          2020: 100_000
      parent2:
        age: 35
      enfant1:
        age: 10
  output:
    rfr: 90_000
    nb_pac: 1
    nbptr: 2.5
    credits_impot: 0
    irpp: -13442
```

@PhunkyBob, l'analyse de la réponse de l'API Web peut aussi être facilitée par l'outil de debug [tracer](https://openfisca.github.io/tracer/) où il suffit d'indiquer `https://fr.openfisca.org/api/latest/` dans le premier champ et la requête dans le dernier pour voir l'ensemble des étapes de calcul.

**Comment by sandcha** [comment]
En complément : nous n'ayons pas la même valeur de taux marginal d'imposition que sur[la page de résultats](https://www3.impots.gouv.fr/simulateur/cgi-bin/calc-2021.cgi?pre_situation_residence=M&pre_situation_famille=M&0DA=1970&0DB=1970&0CF=1&0F0=2010&1AJ=100000) donnée en exemple où il est à `30` quand `ir_taux_marginal` vaut `29.7`.

**Comment by benjello** [comment]
@sandcha : il faut voir si cela ne vient pas du calcul de `taux_effectif`.
Je conseille également de virer la reference de la variable .

**Comment by sandcha** [comment]
Pardon, je me suis aussi embrouillée sur les périodes. Revoici le test yaml où l'on fait figurer `ip_net` : 
```yaml
- name: IRPP
  period: 2021
  input:
    famille:
      parents: [parent1, parent2]
      enfants: [enfant1]
    foyer_fiscal:
      declarants: [parent1, parent2]
      personnes_a_charge: [enfant1]
    menage:
      personne_de_reference: parent1
      conjoint: parent2
      enfants: [enfant1]
    individus:
      parent1:
        age: 42
        revenu_assimile_salaire: 100_000
      parent2:
        age: 35
      enfant1:
        age: 10
  output:
    rfr: 90_000
    nb_pac: 1
    nbptr: 2.5
    credits_impot: 0
    ip_net: 13442
    irpp: -13442
```
