### ISSUE TITLE
Pas d'aide au logement pour locataire à titre gratuit

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1509]
Un test métier a remonté une différence de calcul pour le cas d'un locataire à titre gratuit et sans charge locative.

Commentaire initial :
On vient de me remonter une erreur. Voilà le test YAML pour reproduire

```yaml
- period: 2021-01
  input:
    famille:
      parents: [personne1]
    menage:
      personne_de_reference: personne1
      statut_occupation_logement: locataire_vide
      depcom: 32107
      loyer: 0
      charges_locatives: 0
    individus:
      personne1:
        date_naissance:
          2021-01: 1986-12-01
    foyer_fiscal:
      declarants: [personne1]
  output:
    aide_logement: 0
```

En l'état le montant d'aide au logement est 13€

```
aide_logement@2021-01: [13.68]
```

Test ajouté à l'intégration continue https://app.circleci.com/pipelines/github/openfisca/openfisca-france/627/workflows/601892bb-9baa-4fdc-9062-af744ded549a/jobs/12910

_Originally posted by @guillett in https://github.com/openfisca/openfisca-france/issues/1451#issuecomment-810414578_
