### ISSUE TITLE
Débat sur le formatage des références

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#2002]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by Sasha-Laniece** [comment]
[ decret VS article ]

Lorsqu'on va chercher un décret, on a souvent un texte un peu ardu du type:
>Article 10
A modifié les dispositions suivantes
Modifie [LOI n°2021-1900 du 30 décembre 2021 - art. 61 (V)](https://www.legifrance.gouv.fr/loda/id/LEGIARTI000046673948/2022-12-03/)

En allant cliquer sur `Version > Version Initiale`, on obtient la modification "en clair" :

> Article 10

La seconde colonne du tableau du second alinéa de l'article 61 de la loi n° 2021-1900 du 30 décembre 2021 de finances pour 2022 est ainsi modifiée :
1° A la deuxième ligne, le nombre : « 1 930 485 » est remplacé par le nombre : « 1 931 392 » ;
2° A la dixième ligne, le nombre : « 13 566 » est remplacé par le nombre : « 13 616 » ;
3° A la douzième ligne, le nombre : « 90 667 » est remplacé par le nombre : « 91 358 » ;
4° A la quatorzième ligne, le nombre : « 9 748 » est remplacé par le nombre : « 9 801 » ;
5° A la quinzième ligne, le nombre : « 4 872 » est remplacé par le nombre : « 5 005 » ;
6° A la dix-septième ligne, le nombre : « 35 669 » est remplacé par le nombre : « 35 649 » ;
7° A la dernière ligne, le nombre : « 1 941 470 » est remplacé par le nombre : « 1 942 377 ».

**Comment by Sasha-Laniece** [comment]
[ Quel url est 'propre' ? ]
Les bonnes pratiques.

1 - On mettra toujours l'article ET le décret

2 - Aller le plus possible vers l'url de l'article (et pas le sommaire ou l'entièreté d'un chapitre ou d'un décret)

3 - Ne pas avoir d'informations sur notre recherche dans LégiFrance cachées dans l'url:

OUI:
> https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000046672983

NON:
> https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000046672983/2023-01-19/
> https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000046672983/2022-12-03/#LEGIARTI000046672983

4 - Si les valeurs sont arrêtées par une circulaire/décret:
- on met le lien vers la circulaire/décret
- on met le lien vers l'article de loi qui dit que ce paramètre est fixé par circulaire/décret

**Comment by Sasha-Laniece** [comment]
[Format du champ]

- `href` changer le nom de ce champ ?

**Comment by Sasha-Laniece** [comment]
[ Article ]
Quid d'un article qui est répété tous les ans ?

Idéalement, on met l'url à date de la version:
```
reference:
    2011-01-01:
      - title: Décret 2011-520 du 13/05/2011 - art. 1 (modifie art. 199 decies H du CGI)
        href: https://www.legifrance.gouv.fr/jorf/id/JORFARTI000023995358
      - title: Art. 199 decies H, 3 ter. du CGI
        href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000024020628/2011-05-16/
    2012-01-01:
      - title: Décret 2012-547 du 23/04/2012 (modifie art. 199 decies H du CGI)
        href: https://www.legifrance.gouv.fr/jorf/id/JORFARTI000025743489
      - title: Art. 199 decies H, 3 ter. du CGI
        href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000025746371/2012-04-26/
```

On peut aussi accepter l'url non daté, quitte à rajouter la date plus tard lorsque l'article a changé
