### ISSUE TITLE
DRAFT : Bilan Studieuse #1

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#2003]
Le 19 Janvier 2023, les contributeurs d'OpenFisca-France ont été invités à participer à une réunion de contribution. Ce fut l'occasion d'échanger sur différents points et de prendre ensemble des décisions pour faire avancer le produit.

Dans cette issue, je propose de rédiger l'ensemble des sujets qui ont été abordés et des décisions qui ont été prises afin d'en garder une trace sur le repo.

**Comment by Sasha-Laniece** [comment]
[ 1 - L'HARMONISATION ]
Le chantier d'harmonisation, qui vise à rapprocher les paramètres d'OpenFisca-France de ceux des Barèmes-Ipp afin d'en faire un unique répertoire, a été démarré par @benjello, @sandcha, @eraviart et @Sasha-Laniece au printemps 2021 dans cette issue: https://github.com/openfisca/openfisca-france/issues/1519

Il s'est découpé en de nombreuses actions  résumées ici:
- Initialisation : https://github.com/openfisca/openfisca-france/pull/1537
- 1 - Prélèvements sociaux : https://github.com/openfisca/openfisca-france/issues/1597
- 2 - Impôt sur le revenu : https://github.com/openfisca/openfisca-france/issues/1598
- 3 - Taxation du capital: https://github.com/openfisca/openfisca-france/issues/1599
- 6 - Prestations sociales: https://github.com/openfisca/openfisca-france/issues/1600
- 8 - Chômage et préretraites: https://github.com/openfisca/openfisca-france/issues/1602
- 9 - Marché du travail : https://github.com/openfisca/openfisca-france/issues/1603

Ce qui n'est pas rapproché car inutile dans OpenFisca-France (d'après @benjello )
- 4 - Taxation indirecte : https://github.com/openfisca/openfisca-france/issues/1604 
- 5 - Fiscalité des entreprises: https://github.com/openfisca/openfisca-france/issues/1605
- 7 - Retraite: https://github.com/openfisca/openfisca-france/issues/1601
- 10 - Tarifs réglementés de l'énergie : https://github.com/openfisca/openfisca-france/issues/1606

Pour mener à bien ce travail, il reste encore quelques étapes: 
- [ ] La création d'une tâche de CI pour maintenir le travail d'harmonisation [PR ici](https://github.com/openfisca/openfisca-france/issues/1811) @sandcha 
- [ ] Passer le Validateur yaml de la CI en test 'bloquant' pour empêcher de détricoter l'harmonisation @eraviart 
- [ ] Finir la migration côté IPP ( @benjello )
- [ ] Fusionner les répertoires !

**Comment by Sasha-Laniece** [comment]
[ 2 - LA RFC DE FORMATAGE DES PARAMÈTRES ]
Lors de l'harmonisation, devant la disparité des formats observés dans les paramètres, on s'est posé la question des "bonnes pratiques" quant à la rédaction d'un yaml de paramètres.
S'est ensuivi un débat avec de nombreux échanges tous résumés dans la RFC https://github.com/openfisca/openfisca-france/issues/1672 .
Malheureusement le timing et la charge de travail des différents participants font qu'elle n'a pas été clôturée et les choses sont restées en suspens. Profitant de la présence de nombreux contributeurs lors de la Studieuse, nous avons voulu finaliser cette RFC.

Les actions suivantes ont été prises: 

1 -  Renommage et normalisation des champs des paramètres, avec précision de leur définition dans cette PR https://github.com/openfisca/openfisca-france/issues/1998 . En bref: 
- `description` devient `label`
- `ux_name` devient `short_label`
- `description_en` devient `label_en` 
- `last_review` devient `last_value_still_valid_on`
Ces modifications seront poussées ici: https://github.com/openfisca/openfisca-france/pull/2001, et doivent aussi faire l'objet d'une modification dans `openfisca-core` .

2 - La normalisation du champ `reference` a fait l'objet d'un débat à part. 
En bref, on change le format pour mettre les références à côté de la value qu'elles concernent:
```
label: SMIC brut mensuel
values:
  2022-08-01:
    value: 1678.95
    reference:
        title: Arrêté du 29/07/2022
        href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046113517
  2023-01-01:
    value: 1709.28
    reference:
        title: Décret 2022-1608 du 22/12/2022
        href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046780043
metadata:
    short_label: SMIC brut mensuel
    last_value_still_valid_on: "2022-08-03"
    label_en: Minimum wage - SMIC (1970 -)
```
Ces décisions ont été prises ici : https://github.com/openfisca/openfisca-france/issues/2002 et seront poussées dans une PR à venir (@eraviart )

3 - Toutes ces décisions seront rédigées dans le Wiki, dans la partie Guide des Bonnes Pratiques : https://github.com/openfisca/openfisca-france/wiki/Bonnes-pratiques-de-mod%C3%A9lisation
