### ISSUE TITLE
'salaire_net_a_payer' négatif.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#278]
Bonjour,

Un petit problème avec salaire_net_a_payer , salaire_net qui renvoie des valeurs négatives pour des salaire_de_base proche de 0.  ( au moins ]0, 100] ).

Test yaml ci-dessous : 
- name: "Différent de salaire_de_base"
  period: 2015-03
  input_variables:
    salaire_de_base: 100
  output_variables:
    sali: 0
    salaire_net_a_payer: 0 # TODO: connais pas la valeur exacte, mais supposée > 0
    salaire_net: 0 # TODO: connais pas la valeur exacte, mais supposée > 0
  period: 2015-03
  input_variables:
    salaire_de_base: 100
  output_variables:
    sali: 0
    salaire_net_a_payer: 0 # TODO: connais pas la valeur exacte, mais supposée > 0
    salaire_net: 0 # TODO: connais pas la valeur exacte, mais supposée > 0

**Comment by MattiSG** [comment]
@adrienpacifico Utilise la [syntaxe ` ````` `](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) pour formatter le code  :)

**Comment by adrienpacifico** [comment]
Merci, en espérant que c'est mieux ainsi !

```

- name: "Différent de salaire_de_base"

  period: 2015-03

  input_variables:

    salaire_de_base: 100

  output_variables:

    sali: 0

    salaire_net_a_payer: 0 # TODO: connais pas la valeur exacte, mais
supposée > 0

    salaire_net: 0 # TODO: connais pas la valeur exacte, mais supposée > 0

  period: 2015-03

  input_variables:

    salaire_de_base: 100

  output_variables:

    sali: 0

    salaire_net_a_payer: 0 # TODO: connais pas la valeur exacte, mais
supposée > 0

    salaire_net: 0 # TODO: connais pas la valeur exacte, mais supposée > 0

```


2015-06-25 14:04 GMT+02:00 Matti Schneider <notifications@github.com>:
