### ISSUE TITLE
Décrire les décompositions type en YAML

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#374]
We may refactor the decompositions to use yaml files and separate the tree structure that represents the  imbricated algebraic sums and the attributes of the variables.
@cbenz @laem : what do you think ?

**Comment by cbenz** [comment]
@benjello Dou you have an example which mimics the idea?

**Comment by benjello** [comment]
Nope. But I will produce one ASAP.

**Comment by benjello** [comment]
I shrink the [fiche de paie decomposition] (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/decompositions/fiche_de_paie_decomposition.xml) for an example with only one level of algebraic sum.

```xml
<NODE code="salaire_brut" color="0,99,143" desc="Salaires bruts" shortname="Sal. bruts">
  <NODE code="salsuperbrut" color="0,66,92" desc="Coût du travail" shortname="Coût travail" />
  <NODE code="remboursement_transport" color="0,66,92" desc="Remboursement transport" shortname="Remb. transport" />
  <NODE code="cotisations_employeur" color="249,208,211" desc="Cotisations sociales employeur" shortname="Cot. soc. pat." />
  <NODE code="allegement_fillon" color="0,171,208" desc="Allègement sur les bas salaires (Fillon)" shortname="Allèg. sal." />
  <NODE code="credit_impot_competitivite_emploi" color="0,171,255" desc="Crédit d'impôt compétitivité-emploi" shortname="CICE" />
  <NODE code="tehr" desc="Taxe exceptionnelle sur les hauts revenus" shortname="TEHR" />
</NODE>
```

What about something like the following using yaml syntax:
```yaml
decomposition:
  salaire_brut:
   - salsuperbrut
   - remboursement_transport
   - cotisations_employeur
   - allegement_fillon
   - credit_impot_competitivite_emploi
   - tehr

variables:
  salaire_brut:
    color: 0,99,143
    desc: Salaires bruts
    shortname: Sal. bruts
  salsuperbrut:
    color: 0,66,92
    desc: Coût du travail
    shortname: Coût travail
  remboursement_transport:
    color: 0,66,92
    desc: Remboursement transport
    shortname: Remb. transport
  cotisations_employeur:
    color: 249,208,211
    desc: Cotisations sociales employeur
    shortname: Cot. soc. pat.
  allegement_fillon:
    color: 0,171,208
    desc: Allègement sur les bas salaires (Fillon)
    shortname: Allèg. sal.
  credit_impot_competitivite_emploi:
    color: 0,171,255
    desc: Crédit d'impôt compétitivité-emploi
    shortname: CICE
  tehr:
    desc: Taxe exceptionnelle sur les hauts revenus
    shortname: TEHR
```

**Comment by cbenz** [comment]
At first read the YAML syntax is definitively more readable.

**Comment by laem** [comment]
It looks way better for that simple example, but I'm not sure it will really simplify decomp.xml for instance

**Comment by benjello** [comment]
I do not have a better way of representing a tree of cascading algebraic additions. At least with this scheme we can separate tags from the structure of the tree.

But I am all ears for new proposals ;-)

**Comment by cbenz** [comment]
I like the separation of the tree structure from the variable attributes, in a flat list which does not pollutes the tree.

We could even separate explicitely variables of the `TaxBenefitSystem` from decomposition nodes (algebraic sums) in two flat lists. This would help verification tools #281 and allow to re-use the description. We could store the shortname in `Variable` classes but not colors, which can be specific to each decomposition. We could rename `desc` to `label` and `shortname` to `short_label` to homogenize with `Variable` classes.

My version (to be challenged):

```yaml
decomposition:
  salaire_brut:
   - salsuperbrut
   - remboursement_transport
   - cotisations_employeur
   - allegement_fillon
   - credit_impot_competitivite_emploi
   - tehr

algebraic_sums:
  salaire_brut:
    color: 0, 99, 143
    label: Salaires bruts
    short_label: Sal. bruts

tax_benefit_system_variables:
  salsuperbrut:
    color: 0,66,92
  remboursement_transport:
    color: 0, 66, 92
  cotisations_employeur:
    color: 249, 208, 211
  allegement_fillon:
    color: 0, 171, 208
  credit_impot_competitivite_emploi:
    color: 0, 171, 255
  tehr:
    color: 0, 0, 0
```

For example `remboursement_transport` could become:

```python
class remboursement_transport(Variable):
    column = FloatCol
    entity_class = Individus
    label = u"Remboursement partiel des frais de transport par l'employeur"
    short_label = u"Remb. transport"

    def function(self, simulation, period):
        remboursement_transport_base = simulation.calculate('remboursement_transport_base', period)
        # TODO: paramètres en dur dans le code
        return period, - .5 * remboursement_transport_base
```

**Comment by benjello** [comment]
OK with that. Any known classical guidelines (algorithm ?) for short names ?

**Comment by cbenz** [comment]
I think `short_label` should be written manually because it can be either an initialism (`credit_impot_competitivite_emploi` => `CICE`) or an abbreviation (`remboursement_transport` => `Remb. transport`).

Otherwise we can totally drop the `short_label` attributes and let the (web) client cut the string at N characters, adding a tooltip to reveal the whole `label`.

I still prefer maintaining beautiful short labels :)

**Comment by benjello** [comment]
I agree with you, i was only asking about guidelines for clean abbreviating (or acronym) of french long names.

**Comment by cbenz** [comment]
Sorry then :)

**Comment by laem** [comment]
> My version (to be challenged):

Nice ! I would call variable types `virtual variables` or `sum variables` and simply `variables` but yours is more precise. 

I still don't see how the tree would be represented in YAML :cry:

**Comment by benjello** [comment]
May be it is because I didn't went deep enough.
grand_sum = intermediate_sum_1 + intermediate_sum_2 + item_3
                   = (item_1_1 + item_1_2) + (item_2_1 + item_2_2) + item_3 

````yaml
grand_sum:
  - intermediate_sum_1:
     - item_1_1
     - item_1_2
  - intermediate_sum_2:
    - item_2_1
    - item_2_2
  - item_3
````

**Comment by laem** [comment]
In your `grand_sum` list you'll have both objects with a single attribute and strings, but I guess that's OK

**Comment by benjello** [comment]
You can do a more verbose representation:
````yaml
grand_sum:
  - intermediate_sum_1:
  - intermediate_sum_2:
  - item_3
intermediate_sum_1:
  - item_1_1
  - item_1_2
intermediate_sum_2:
  - item_2_1
  - item_2_2
  ````

But then you would have to check that there is no typos, no infinite loops etc
