### ISSUE TITLE
L'irpp/decote sont faux en 2013

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#398]
La décote est fausse en 2013 pour les bas revenus (ceux concernés par la décote).
@benjello je subodore que c'est les abattements Valls ? T'as codé quelque chose pour la note de l'IPP ?

voir #399

**Comment by benjello** [comment]
Je crois que c'est peut-être bon si @claireleroy a regardé mais peut-être qu'elle n'est aps remonté aussi loin

**Comment by Morendil** [comment]
Effectivement en réintégrant les trois cas de tests notés "Non passant" je constate des erreurs.

Il convient d'abord de transformer l'IR en une valeur négative dans les tests, cela transforme un des cas "Non passant" en un cas passant, celui pour le revenu de 16000€. Le cas pour un revenu de 12000€ est en fait passant. Il reste donc un seul KO sur le revenu imposable de 14000€.

Le seuil de la décote 2013 est correct.

La réduction Valls (`reduction_impot_exceptionnelle`) est bien calculée, par contre elle ne semble pas être appliquée à `ir_plaf_qf` l'IR après calcul du quotient et plafonnement: l'évolution de celui-ci entre 2012 et 2013 est minime, de 424€ en 202 à 414€ en 2013. Cette réduction n'est prise en compte que dans le calcul de la variable `irpp`. Je le vérifie empiriquement avec un test qui force la réduction exceptionnelle et constate que `ir_plaf_qf` est inchangé.

Je ne connais pas suffisamment la logique du calcul de l'impôt et de ses réductions pour avoir une piste de solution à proposer.

Je note par contre que si une confusion a pu se produire pour une réduction exceptionnelle, il est possible qu'elle ait concerné d'autres réductions, je vois donc dans cette issue un risque potentiel.

Sujet mineur: la notion exprimée par la variable `decote_gain_fiscal` n'est pas claire, elle n'est utilisée nulle part en dehors des tests irpp.yaml, elle mériterait une référence législative ou documentaire si elle a un sens métier (une recherche sur le web n'a pas pu m'éclairer à ce sujet).

Ci-dessous les tests complémentaires à insérer dans `irpp.yaml`:

```
- name: "IRPP - Célibataire ayant des   Revenu net imposable de 12 000 € (teste la décote)"
  period: 2013
  absolute_error_margin: 0.9 #TODO : check why the error margin is so large, is there bottom round made by dgfip ?
  input_variables:
    salaire_imposable: 12000
  output_variables:
     irpp: 0
     decote_gain_fiscal: 263

- name: "IRPP - Célibataire ayant des   Revenu net imposable de 14 000 € (teste la décote) force la réduction exceptionnelle"
  period: 2013
  absolute_error_margin: 9.9 #TODO : check why the error margin is so large, is there bottom round made by dgfip ?
  input_variables:
    salaire_imposable: 14000
    reduction_impot_exceptionnelle: 50000
  output_variables:
     ir_plaf_qf: 414
     irpp: 0

- name: "IRPP - Célibataire ayant des   Revenu net imposable de 14 000 € (teste la décote) non passant"
  period: 2013
  absolute_error_margin: 9.9 #TODO : check why the error margin is so large, is there bottom round made by dgfip ?
  input_variables:
    salaire_imposable: 14000
  output_variables:
     reduction_impot_exceptionnelle: 350
     irpp: 0
     decote: 238
     ir_plaf_qf: 414
     decote_gain_fiscal: 238

- name: "IRPP - Célibataire ayant des   Revenu net imposable de 16 000 € (teste la décote)"
  period: 2013
  absolute_error_margin: 0.9 #TODO : check why the error margin is so large, is there bottom round made by dgfip ?
  input_variables:
    salaire_imposable: 16000
  output_variables:
    irpp: -491
    decote_gain_fiscal: 175
```
